# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-text-plugin-system',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-text-plugin-system',
                'lib_path': 'cjm_text_plugin_system'},
  'syms': {}}
